[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "qemu-system-x86_64 -bios /usr/share/ovmf/OVMF.fd -drive format=raw,file=fat:rw:target/x86_64-unknown-uefi/debug/ -net none -nographic"

[target.aarch64-unknown-uefi]
runner = "qemu-system-aarch64 -bios /usr/share/ovmf/OVMF.fd -drive format=raw,file=fat:rw:target/aarch64-unknown-uefi/debug/ -net none -nographic"
