# Reduce replicas for staging to save resources
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh
spec:
  replicas: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osteon
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myocyte
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circadian
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaperone
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdpr
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  replicas: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mesh-hpa
spec:
  minReplicas: 1
  maxReplicas: 4

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: osteon-hpa
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myocyte-hpa
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: synapse-hpa
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: circadian-hpa
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nucleus-hpa
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chaperone-hpa
spec:
  minReplicas: 1
  maxReplicas: 3

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gdpr-hpa
spec:
  minReplicas: 1
  maxReplicas: 3
