[package]
name = "ea-dreamer"
version = "0.1.0"
edition = "2021"
authors = ["Ea Foundation"]
description = "Dreamer - Integrity Engine Muscle"

[dependencies]
muscle-contract = { path = "../../muscle-contract", default-features = false }

[lib]
crate-type = ["rlib"]
