[package]
name = "pre-nucleus-loader"
version = "0.1.0"
description = "2KiB pre-nucleus loader - verifies and loads Nucleus Muscle"
authors = ["EÃ¤ Foundation"]
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "preloader"
path = "src/lib.rs"

[dependencies]
muscle-contract = { path = "../../muscle-contract", default-features = false }
